//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTCsharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP
    {
        public string Art_SP { get; set; }
        public int Cam { get; set; }
        public int Thick_SP { get; set; }
        public int Thick_Glass { get; set; }
        public int id { get; set; }
    }
}
